### ISSUE TITLE
Update this repo to use the latest schema from PM

### ISSUE THREAD

**Issue by mskyttner** [DINA-Web/collections-data-model-docker#10]
A first draft of a full schema is available since mid  July:

https://github.com/chicoreus/cco_poc/blob/master/src/main/resources/edu/harvard/huh/specify/datamodel/cco_full/db/tables.sql

This repo should be updated to use it, I suggest a pull request to update the
https://github.com/DINA-Web/collections-data-model and merging that when
the https://github.com/DINA-Web/collections-data-model-docker builds
correctly and provides access to that fleshed out schema through the
"make connect" command.

**Comment by Inkimar** [comment]
fixed in #11
